name: Deployment
 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: 'cd /var/www/cs-pricepred && ./deploy.sh'
